import "./global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1 className="text-blue-500">Our App</h1>
          <nav className="bg-gray-800 text-white p-4">
            <ul className="flex space-x-4">
              <li><a href="/">Home</a></li>
              <li><a href="/login">Login</a></li>
            </ul>
          </nav> 
        </header>
        {children}
        <footer>2025</footer>
      </body>
    </html>
  )
}
