import "./global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
      
        </header>
        {children}
        <footer>2025</footer>
      </body>
    </html>
  )
}
