'use client';

import { Download } from 'lucide-react';

interface DownloadButtonProps {
  fileName: string;
  title: string;
  date: string;
  summary: string;
}

export function DownloadButton({ fileName, title, date, summary }: DownloadButtonProps) {
  const handleDownload = () => {
    const content = `
${title}

Uploaded on: ${date}

${summary}

Generated by OPSOM
    `.trim();

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.txt`;
    a.click();

    // Delay revoking the object URL to ensure the download is triggered
    setTimeout(() => {
      URL.revokeObjectURL(url);
    }, 100);
  };

  return (
    <button
      onClick={handleDownload}
      className="inline-flex items-center gap-2 px-4 py-2 rounded-md bg-indigo-600 text-white hover:bg-indigo-700 transition shadow-sm"
    >
      <Download /> Download
    </button>
  );
}
