'use client';

interface DownloadButtonProps {
  fileName: string;
  title: string;
  date: string;
  summary: string;
}

export function DownloadButton({ fileName, title, date, summary }: DownloadButtonProps) {
  const handleDownload = () => {
    const content = `
${title}

Uploaded on: ${date}

${summary}

Generated by OPSOM
    `.trim();

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.txt`;
    a.click();

    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleDownload}
      className="mt-4 px-4 py-2 bg-indigo-600 text-white rounded hover:bg-indigo-700 transition"
    >
      Download TXT
    </button>
  );
}
